const express = require("express");
const app = express();
app.use(express.json());
const cors = require("cors");
app.use(cors());
// app.options("*", cors());
const globalErrors = require("./controllers/errControllers");
app.use(globalErrors);
module.exports = app;
console.log("IN THE APP FILE");
